runtime: nodejs20
# default_expiration: "1d"
instance_class: F2

handlers:
- url: /assets/images
static_dir: images

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto