steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install', '--ignore-engines']
- name: 'node'
  entrypoint: 'yarn'
  args: ['test', '--ignore-engines']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--ignore-engines']
options:
  logging: CLOUD_LOGGING_ONLY

timeout: 2400s