steps:
- name: 'node-16'
  entrypoint: 'yarn'
  args: ['install']
- name: 'node-16'
  entrypoint: 'yarn'
  args: ['test']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
options:
  logging: CLOUD_LOGGING_ONLY