steps:
- name: 'gcr.io/cloud-builders/yarn:node-16'
  args: ['install', '--ignore-engines']
  dir: 'functions/autodeploy'

- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  args: ['test']
  dir: 'functions/autodeploy'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'someName', '--trigger-topic', 
  'some.topic.name', '--runtime', 'nodejs10']
  dir: 'functions/autodeploy'