steps:
- name: 'gcr.io/cloud-builders/yarn:node-16'
  args: ['install', '--ignore-engines']
  dir: 'functions/autodeploy'

- name: 'gcr.io/cloud-builders/npm:node-16'
  args: ['test']
  dir: 'functions/autodeploy'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'someName', '--trigger-topic', 
  'some.topic.name', '--runtime', 'nodejs16']
  dir: 'functions/autodeploy'
  logging: CLOUD_LOGGING_ONLY